# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jordan and Justin's wedding!
email: justin@jbarr.co
description: > # this means to ignore newlines until "baseurl:"
  Jordan and Justin are getting married!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://JordanAndJustin.com" # the base hostname & protocol for your site
twitter_username: theJayBeeWhy
github_username:  jay-bee-why

# Build settings
markdown: kramdown

gems: [jekyll-slim]
 # This will require each of these gems automatically.
